#!/bin/bash
DIR=`pwd`
DOMAIN_NAME=`basename "$DIR"`
export AWS_DEFAULT_PROFILE=`echo $DOMAIN_NAME | sed -e 's/\./\-/g'`
aws configure --profile $AWS_DEFAULT_PROFILE

if [ $# -eq 0 ]; then
  aws s3 cp s3://$DOMAIN_NAME . --exclude ".*"
else
  aws s3 cp s3://$DOMAIN_NAME/$1 .
fi
