#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Usage: $0 create|update <DOMAIN_NAME>"
  echo "e.g. $0 create example.com"
  exit 1
else
  # We need a unique "stackname" for CloudFormation,
  # however CF doesn't accept periods in stack-names
  STACK_NAME=`echo $2 | sed -e 's/\./\-/g'`

  # Configures the aws-cli - requires an access key id and secret
  # http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
  export AWS_DEFAULT_PROFILE=exe-$STACK_NAME
  aws configure --profile $AWS_DEFAULT_PROFILE
  
  # Run the CF command with our parameters and the template.json
  aws cloudformation $1-stack \
    --stack-name $AWS_DEFAULT_PROFILE \
    --template-body file://template.json \
    --capabilities CAPABILITY_IAM \
    --parameters ParameterKey=DomainName,ParameterValue=$2
fi
